nvidiaInstaller:
  namespace: kube-system
  image: squat/modulus
  tag: 4a1799e7aa0143bcbb70d354bab3e419b1f54972
  driverVersion: 410.104
  hostDriverPath: /opt/drivers
  nodeSelector: {}
  nodeAffinity: {}
  # Example:
  #  nodeAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      nodeSelectorTerms:
  #        - matchExpressions:
  #            - key: gpu
  #              operator: Exists
  tolerations:
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"

nvidiaDevicePlugin:
  namespace: kube-system
  image: k8s.gcr.io/nvidia-gpu-device-plugin@sha256
  tag: 08509a36233c5096bb273a492251a9a5ca28558ab36d74007ca2a9d3f0b61e1d
  pauseImage: k8s.gcr.io/pause-amd64
  pauseTag: 3.1
  hostDevicePluginPath: /var/lib/kubelet/device-plugins
  nodeSelector: {}
  nodeAffinity: {}
  tolerations:
   - key: CriticalAddonsOnly
     operator: Exists
   - key: "nvidia.com/gpu"
     operator: "Exists"
     effect: "NoSchedule"
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi