apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "nvidia-device-plugin.fullname" . }}
  namespace: {{ .Values.nvidiaDevicePlugin.namespace }}
  labels:
    app: {{ template "nvidia-device-plugin.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        name: {{ template "nvidia-device-plugin.name" . }}
        k8s-app: {{ template "nvidia-device-plugin.name" . }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      volumes:
      - name: device-plugin
        hostPath:
          path: {{ required "nvidia-device-plugin.hostDevicePluginPath" .Values.nvidiaDevicePlugin.hostDevicePluginPath }}
      - name: dev
        hostPath:
          path: /dev
      containers:
      - image: {{ printf "%s:%s" .Values.nvidiaDevicePlugin.image .Values.nvidiaDevicePlugin.tag }}
        command:
        - "/usr/bin/nvidia-gpu-device-plugin"
        - "-logtostderr"
        - {{ printf "-host-path=%s/nvidia" .Values.nvidiaInstaller.hostDriverPath }}
        name: nvidia-gpu-device-plugin
        resources:
{{ toYaml .Values.nvidiaDevicePlugin.resources | indent 12 }}
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
{{- if .Values.nvidiaDevicePlugin.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nvidiaDevicePlugin.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.nvidiaDevicePlugin.tolerations }}
      tolerations:
{{ toYaml .Values.nvidiaDevicePlugin.tolerations | indent 6 }}
{{- end }}
  updateStrategy:
    type: RollingUpdate